# Pandas 기초 & Titanic 데이터셋 실습

오늘은 데이터 분석에서 가장 많이 쓰이는 라이브러리인 **pandas**의 기본기를 실습했다. `Series`(1차원)와 `DataFrame`(2차원 표) 두 가지 핵심 자료구조를 만들어보고, 실제 Titanic CSV 데이터를 불러와서 컬럼 선택, 조건 필터링, `loc`/`iloc` 인덱싱까지 연습했다.

## 1. pandas 설치 & 임포트

pandas가 설치되어 있지 않다면 주석 처리된 `!pip install pandas`의 주석을 풀고 실행하면 된다. (이미 설치되어 있어서 주석 처리된 상태로 둠)

In [1]:
# 설치가 안 되어 있는 경우에만 아래 주석을 풀고 실행 (이미 설치돼 있으므로 주석 처리해둠)
# !pip install pandas

Collecting pandas
  Using cached pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in .\.venv\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
Using cached tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.5 tzdata-2026.4

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

pandas는 관례적으로 `pd`라는 별칭(alias)으로 임포트한다.

In [4]:
import pandas as pd  # 관례적으로 pandas는 pd라는 별칭으로 임포트한다.

## 2. 딕셔너리로 DataFrame 만들기

`DataFrame`은 엑셀 시트처럼 행과 열이 있는 2차원 표 자료구조다. 딕셔너리를 넘기면 **key가 컬럼명, value 리스트가 각 컬럼의 값들**이 된다.

In [5]:
# 딕셔너리의 key -> 컬럼명, value(리스트) -> 그 컬럼의 값들이 된다.
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

## 3. 리스트로 Series 만들기 (기본 정수 인덱스)

`Series`는 컬럼 하나에 해당하는 1차원 자료구조다. 리스트만 넘기면 인덱스가 자동으로 0부터 매겨진다.

In [8]:
a = [1, 7, 2]
# 인덱스를 따로 지정하지 않으면 0, 1, 2, ... 순서로 자동 부여된다.
myvar1 = pd.Series(a)
print(myvar1)

0    1
1    7
2    2
dtype: int64

정수 인덱스로 특정 위치의 값을 꺼낼 수 있다 (리스트처럼 0부터 시작).

In [14]:
print(myvar1[1])  # 인덱스 1번(두 번째) 값을 출력

7

## 4. 인덱스를 직접 지정한 Series

`index` 파라미터로 각 값에 이름표를 붙일 수 있다. 이후에는 숫자 대신 이 이름으로 값을 조회할 수 있다.

In [10]:
# index를 직접 지정하면 각 값에 원하는 이름표를 붙일 수 있다.
myvar2 = pd.Series(a, index = ["x", "y", "z"])
print(myvar2)

x    1
y    7
z    2
dtype: int64

지정한 라벨(`"y"`)로 값을 조회한다.

In [13]:
print(myvar2["y"])  # 라벨 "y"에 해당하는 값 조회

7

## 5. 딕셔너리로 Series 만들기

딕셔너리를 `Series`에 넘기면 **key가 그대로 인덱스(라벨)** 가 된다.

In [16]:
# 딕셔너리를 Series로 만들면 key가 인덱스(라벨)로 그대로 쓰인다.
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar3 = pd.Series(calories)

print(myvar3)

day1    420
day2    380
day3    390
dtype: int64

## 6. 여러 컬럼을 가진 DataFrame

컬럼이 2개 이상인 딕셔너리를 넘기면 그대로 여러 컬럼을 가진 표가 만들어진다.

In [18]:
# 컬럼이 여러 개인 딕셔너리 -> 여러 컬럼을 가진 DataFrame이 된다.
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar4 = pd.DataFrame(data)

print(myvar4)

   calories  duration
0       420        50
1       380        40
2       390        45

## 7. 사람 정보로 DataFrame 만들기

이름, 나이, 성별 3개 컬럼을 가진 작은 DataFrame을 만든다. 이후 Titanic 데이터를 다루기 전, DataFrame의 기본 동작(컬럼 선택, 통계 함수 등)을 먼저 연습해본다.

In [29]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)

만든 DataFrame 전체를 출력해서 확인한다.

In [30]:
print(df)

                       Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2   Bonnell, Miss Elizabeth   58  female

`df["컬럼명"]`으로 특정 컬럼 하나만 선택할 수 있다. 결과는 `Series`다.

In [31]:
print(df["Age"])  # "Age" 컬럼만 선택 -> Series로 반환됨

0    22
1    35
2    58
Name: Age, dtype: int64

`name` 파라미터로 Series에 이름을 붙일 수도 있다 (DataFrame의 컬럼처럼 취급하기 좋음).

In [33]:
ages = pd.Series([22,35,58], name="Age")
print(ages)

0    22
1    35
2    58
Name: Age, dtype: int64

Series/컬럼에는 `.max()`, `.min()`, `.mean()` 같은 통계 메서드를 바로 쓸 수 있다.

In [34]:
df["Age"].max()  # Age 컬럼의 최댓값

np.int64(58)

`.describe()`는 숫자형 컬럼들에 대한 요약 통계(개수, 평균, 표준편차, 최소/최대, 사분위수 등)를 한 번에 보여준다.

In [35]:
df.describe()  # 숫자형 컬럼들에 대한 요약 통계량 한 번에 확인

             Age
count   3.000000
mean   38.333333
std    18.230012
min    22.000000
25%    28.500000
50%    35.000000
75%    46.500000
max    58.000000

## 8. 실제 데이터셋 불러오기: Titanic

`pd.read_csv()`로 `data/titanic.csv` 파일을 읽어서 DataFrame으로 만든다. 여기서부터는 앞서 연습한 작은 예제 대신 실제 승객 데이터를 다룬다.

In [37]:
# data/titanic.csv 파일을 읽어서 DataFrame으로 만든다.
titanic = pd.read_csv("data/titanic.csv")

변수명만 입력해서(=주피터의 마지막 표현식 자동 출력) 전체 데이터를 표 형태로 확인한다.

In [39]:
titanic  # 노트북에서 변수명만 쓰면 표 형태로 예쁘게 출력해준다.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

`.head(n)`으로 앞에서부터 n개 행만 미리 본다 (기본값은 5개).

In [40]:
titanic.head(8)  # 앞에서 8개 행만 미리보기

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

`.dtypes`로 각 컬럼의 데이터 타입(정수, 실수, 문자열 등)을 확인한다.

In [38]:
titanic.dtypes  # 각 컬럼의 데이터 타입 확인

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

## 9. CSV ↔ Excel 변환

`.to_excel()`로 DataFrame을 엑셀 파일로 저장할 수 있다. `sheet_name`으로 시트 이름을, `index=False`로 행 인덱스는 저장하지 않도록 지정한다.

In [43]:
# DataFrame을 엑셀 파일로 저장. index=False로 행 번호(인덱스)는 저장하지 않는다.
titanic.to_excel("titanic.xlsx", sheet_name="passengers", index=False)

반대로 `.read_excel()`로 방금 저장한 엑셀 파일을 다시 읽어와 DataFrame으로 복원한다.

In [44]:
# 저장했던 엑셀 파일을 다시 읽어서 DataFrame으로 복원한다.
titanic = pd.read_excel("titanic.xlsx", sheet_name="passengers")

`.info()`는 각 컬럼의 이름, non-null 개수, 데이터 타입, 메모리 사용량 등을 한 번에 요약해서 보여준다. 결측치(비어있는 값)가 있는 컬럼을 파악할 때 유용하다.

In [45]:
titanic.info()  # 컬럼별 결측치 개수, 타입, 메모리 사용량 등 요약 정보

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

## 10. 컬럼 하나 선택하기 (Series로 반환)

`titanic["Age"]`처럼 대괄호에 컬럼명 하나를 넣으면 그 컬럼이 `Series`로 반환된다.

In [46]:
ages = titanic["Age"]  # 컬럼 하나 선택 -> Series 반환

선택한 `ages` Series의 앞부분을 미리 확인한다.

In [47]:
ages.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

실제 타입을 확인해서 컬럼 하나를 선택하면 `Series`가 된다는 것을 검증한다.

In [48]:
type(titanic["Age"])  # pandas.core.series.Series

pandas.Series

`.shape`로 (행 개수,) 형태의 크기를 확인한다. Series는 1차원이라 튜플에 값이 하나뿐이다.

In [49]:
titanic["Age"].shape  # (행 개수,) - Series는 1차원이므로 값이 하나

(891,)

## 11. 컬럼 여러 개 선택하기 (DataFrame으로 반환)

대괄호를 두 번 겹쳐서 `titanic[["Age", "Sex"]]`처럼 **컬럼명 리스트**를 넘기면, 결과는 Series가 아니라 그 컬럼들만 담은 `DataFrame`이 된다.

In [51]:
# 컬럼명 리스트를 넘기면 여러 컬럼을 가진 DataFrame이 반환된다.
age_sex = titanic[["Age", "Sex"]]
age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

컬럼을 리스트로 선택하면 타입이 `Series`가 아니라 `DataFrame`이 된다는 것을 확인한다.

In [52]:
type(titanic[["Age", "Sex"]])  # pandas.core.frame.DataFrame

pandas.DataFrame

`.shape`로 (행 개수, 열 개수) 형태의 크기를 확인한다. 이번엔 컬럼이 2개이므로 값이 두 개다.

In [53]:
titanic[["Age", "Sex"]].shape  # (행 개수, 열 개수) - 컬럼 2개짜리 DataFrame

(891, 2)

## 12. 조건으로 행 필터링하기

`titanic["Age"] > 35`처럼 조건식을 대괄호 안에 넣으면, 그 조건을 만족하는 행만 걸러낼 수 있다. (SQL의 `WHERE`와 비슷한 역할)

In [55]:
# 조건식을 대괄호에 넣으면 조건을 만족하는 행만 걸러낸 DataFrame을 반환한다.
above_35 = titanic[titanic["Age"] > 35]
above_35.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S

조건식 `titanic["Age"] > 35` 자체는 각 행이 조건을 만족하는지(True/False)를 담은 **불리언 Series**다. 이 불리언 Series를 다시 대괄호에 넣는 것이 필터링의 원리다.

In [56]:
titanic["Age"] > 35  # 각 행마다 조건 만족 여부(True/False)를 담은 불리언 Series

0      False
1       True
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

필터링된 결과(`above_35`)의 크기를 확인해서 몇 명이 조건을 만족했는지 본다.

In [57]:
above_35.shape  # 35세 초과 승객의 (행 개수, 열 개수)

(217, 12)

`|`(OR)로 여러 조건을 결합할 수도 있다. 여기서는 `Pclass`(선실 등급)가 2등석 **또는** 3등석인 승객만 필터링한다. 각 조건은 반드시 괄호로 감싸야 한다 (파이썬 연산자 우선순위 때문).

In [58]:
# | (OR)로 여러 조건 결합. 각 조건은 괄호로 감싸야 한다.
class_23 = titanic[(titanic["Pclass"] == 2) | (titanic["Pclass"] == 3)]
class_23.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

## 13. loc / iloc로 행과 열을 동시에 선택하기

`.loc[행조건, 열이름]`은 **라벨(이름) 기준**으로 행과 열을 동시에 선택한다. 여기서는 "나이가 35세 초과인 행"의 "Name" 컬럼만 뽑아낸다.

In [60]:
# .loc[행조건, 열이름] : 라벨 기준으로 행/열을 동시에 선택.
# "Age > 35"인 행들 중에서 "Name" 컬럼만 뽑는다.
adult_names = titanic.loc[titanic["Age"] > 35, "Name"]
adult_names.head()

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
6                               McCarthy, Mr. Timothy J
11                              Bonnell, Miss Elizabeth
13                          Andersson, Mr. Anders Johan
15                     Hewlett, Mrs. (Mary D Kingcome)
Name: Name, dtype: str

`.iloc[행범위, 열범위]`는 **정수 위치(순서) 기준**으로 선택한다. 여기서는 10번째~24번째 행(`9:25`)의, 3번째~5번째 열(`2:5`)을 잘라낸다. 슬라이싱이라 끝 인덱스는 포함되지 않는다.

In [61]:
# .iloc[행범위, 열범위] : 정수 위치(순서) 기준으로 선택.
# 인덱스 9~24번 행(10~25번째), 2~4번 열(3~5번째)을 잘라낸다.
titanic.iloc[9:25, 2:5]

    Pclass                                               Name     Sex
9        2                Nasser, Mrs. Nicholas (Adele Achem)  female
10       3                     Sandstrom, Miss Marguerite Rut  female
11       1                            Bonnell, Miss Elizabeth  female
12       3                     Saundercock, Mr. William Henry    male
13       3                        Andersson, Mr. Anders Johan    male
14       3                Vestrom, Miss Hulda Amanda Adolfina  female
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female
16       3                                Rice, Master Eugene    male
17       2                       Williams, Mr. Charles Eugene    male
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19       3                            Masselmani, Mrs. Fatima  female
20       2                               Fynney, Mr. Joseph J    male
21       2                              Beesley, Mr. Lawrence    male
22       3                         McGowan, Miss Anna "Annie"  female
23       1                       Sloper, Mr. William Thompson    male
24       3                       Palsson, Miss Torborg Danira  female